# Generated by Django 3.0.4 on 2020-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ayurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='disps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='neuts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pharms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='respis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='surgis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100)),
                ('item2', models.CharField(max_length=100)),
                ('item3', models.CharField(max_length=100)),
            ],
        ),
    ]
