# Generated by Django 3.0.4 on 2020-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuts',
            name='item4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharms',
            name='item4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='respis',
            name='item4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surgis',
            name='item4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allos',
            name='item1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allos',
            name='item2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allos',
            name='item3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ayurs',
            name='item1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ayurs',
            name='item2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ayurs',
            name='item3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disps',
            name='item1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disps',
            name='item2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disps',
            name='item3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neuts',
            name='item1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neuts',
            name='item2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neuts',
            name='item3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharms',
            name='item1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharms',
            name='item2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharms',
            name='item3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respis',
            name='item1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respis',
            name='item2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respis',
            name='item3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surgis',
            name='item1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surgis',
            name='item2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surgis',
            name='item3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
