# Generated by Django 3.0.4 on 2020-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200404_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='allos',
            name='item4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ayurs',
            name='item4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disps',
            name='item4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
