# Generated by Django 3.0.4 on 2020-04-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200404_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='applys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cervis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fingers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='kneees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='neops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wrists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
