# Generated by Django 3.0.4 on 2020-04-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_cathes_dias_flus_osiis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='osiis',
        ),
    ]
